org.gradle.jvmargs=-Xmx2G
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
loader_version=0.18.4
fabric_version=0.116.4+1.21.1
mod_version=0.1.0+mc1.21.1
maven_group=cn.sh1rocu
archives_base_name=touhoulittlemaid-addon-eschest
main_mod_version=0.7.0-neo1.5.2+mc1.21.1
